FROM openjdk:8u282-jre-slim-buster as builder
WORKDIR /app
ADD target/mac-docker-1.0-SNAPSHOT.jar ./
RUN java -Djarmode=layertools -jar mac-docker-1.0-SNAPSHOT.jar extract

FROM openjdk:8u282-jre-slim-buster
WORKDIR /app
COPY --from=builder app/dependencies ./
COPY --from=builder app/spring-boot-loader ./
COPY --from=builder app/snapshot-dependencies ./
COPY --from=builder app/application ./
EXPOSE 8080
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
